
spring:
  application:
    name: ideploy-web  #应用名

  thymeleaf:
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      cache: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ideploy?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: ideploy
    password: zh@SBN/7
    druid:
      timeBetweenLogStatsMillis: 300000
      minIdle: 1
      validationQuery: SELECT 'x'
      initialSize: 1
      maxWait: 60000
      filters: stat,wall,log4j
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      testWhileIdle: true
      testOnBorrow: false
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      testOnReturn: false
      maxActive: 40

  redis:
    url: redis://localhost:6379
    ssl: false
    timeout: 0
    jedis:
      pool:
        max-idle: 8 # 池中“空闲”连接的最大数量。使用负值表示无限数量的空闲连接。
        min-idle: 0 # 目标为保持在池中的最小空闲连接数。这个设置只有在正面的情况下才有效果。
        max-active: 8  #池在给定时间可以分配的最大连接数。使用负值无限制。
        max-wait: -1   # 连接分配在池被耗尽时抛出异常之前应该阻塞的最长时间量（以毫秒为单位）。使用负值可以无限期地阻止

